services:
    ant.admin.news:
        class: Ant\Bundle\Admin\NewsAdmin
        arguments: [~, Ant\Bundle\Entity\News, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News}

    ant.admin.portfolio:
        class: Ant\Bundle\Admin\PortfolioAdmin
        arguments: [~, Ant\Bundle\Entity\Portfolio, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Portfolio}
